### ISSUE TITLE
ImportError: No module named blacklist_support

### ISSUE THREAD

**Issue by jack51706** [sivaramakrishnansr/BLAG#1]
generate_prefix_data.py", line 6, in <module>
    from blacklist_support import check_overlap,half_life,parser
ImportError: No module named blacklist_support

Is there any file missing ?

**Comment by ypoplary** [comment]
> generate_prefix_data.py", line 6, in
> from blacklist_support import check_overlap,half_life,parser
> ImportError: No module named blacklist_support
> 
> Is there any file missing ?

I think you need to change the "blacklist_support" to "blag_support", you can try it.

**Comment by sivaramakrishnansr** [comment]
Hey guys. 

Apologies for the late response. The code has been fixed. The current version also processes blacklists to generate an intermediate file that helps to generate recommendation scores faster. Let me know if you have any other issues.
